# Use prebuilt image with Maven, Chrome, ChromeDriver
FROM markhobson/maven-chrome:latest

# Set working directory
WORKDIR /usr/src/app

# Copy the entire project
COPY . .

# Run tests using Maven
CMD ["mvn", "test"]









